services:
  router:
    build:
      context: ./docker/router
    environment:
      - EXAMPLE_UPSTREAM=pwa:3000

  php:
    environment:
      - APP_ENV=dev # Needed for fixtures bundles to work.
      - APP_SECRET=${APP_SECRET}
      - XDEBUG_MODE='off'

  pwa:
    build:
      target: gally_pwa_int
      args:
        - public_url=https://${SERVER_NAME:-${PWA_SERVER_NAME:-gally.localhost}}/example
