services: # TODO upgrade : test ci
  pwa:
    build:
      context: ./front
      target: gally_pwa_ci
    volumes:
      - ./front/example-app/coverage:/usr/src/front/example-app/coverage:rw,cached,z
      - ./front/pwa/coverage:/usr/src/front/pwa/coverage:rw,cached,z

  example:
    build:
      context: ./front
      target: gally_example_ci
