services:
  php:
    build:
      context: ./api
      target: gally_php_dev
    volumes: !override
      - ./api:/app:rw,cached,z
      - ./api/docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro,z
    environment:
      APP_ENV: dev
      XDEBUG_MODE:  off

  pwa:
    build:
      context: ./front
      target: gally_pwa_ci
    volumes:
      - ./front/example-app/coverage:/usr/src/front/example-app/coverage:rw,cached,z
      - ./front/pwa/coverage:/usr/src/front/pwa/coverage:rw,cached,z

  example:
    build:
      context: ./front
      target: gally_example_ci
