
version: "3.4"

# Production environment override
services:
  php:
    environment:
      APP_ENV: dev # Needed for fixtures bundles to work.

  caddy:
    environment:
      EXAMPLE_UPSTREAM: pwa:3000
    networks:
      default:
        aliases:
          - ifpen.gally.dev


  pwa:
    build:
      context: ./front
      target: gally_pwa_int
      args:
        public_url: https://${SERVER_NAME}/example
    volumes:
      - /home/ubuntu/data/gael_files:/usr/src/front/pwa/public/gael_files:rw,cached,z
      - /home/ubuntu/data/prisme_files:/usr/src/front/pwa/public/prisme_files:rw,cached,z

