name: CI

on:
  push:
    branches:
      - master
      - 1.0.x
      - feature-boost
  pull_request:
    branches:
      - master
      - 1.0.x
      - feature-boost
    types: [review_requested, ready_for_review, synchronize]
  workflow_dispatch: ~

jobs:
  tests:
    if: github.event.pull_request.draft == false
    name: Tests
    uses: ./.github/workflows/tests.yml
    secrets: inherit
